FROM tensorflow/tensorflow:latest-gpu

RUN pip install Pillow==6.1.0
RUN pip install scikit-image==0.15.0
RUN pip install scikit-learn==0.21.2
RUN pip install scipy==1.1.0
RUN pip install pydot
RUN apt-get update
RUN apt-get install graphviz -y